### ISSUE TITLE
Getting id of asset always null

### ISSUE THREAD

**Issue by ghost** [bigchaindb/java-bigchaindb-driver#23]
When i invoke
Transaction lastTransaction  = TransactionsApi.getTransactionById(id); - here i get not null trasaction
Asset asset = lastTransaction.getAsset() - here i get not null asset
asset.getId() - here i get null, but when i check asset id in mongo it is not null

**Comment by innopreneur** [comment]
Hey @NikitaLos ,

`Asset Id` needs to be retrieved in different ways depending on the fetched Transaction was `CREATE` tx or `TRANSFER` tx. You are getting `null` asset id, because you are fetching from `CREATE` tx.  Structure for Tx object/ json for CREATE and TRANSFER tx are different. So, asset id needs to be fetched differently.

Below is a sample method to get asset id for both types of transactions. Hope it helps -

```
public String getAssetId(String txId) throws IOException {
		String assetId = null;
		//get the transaction
		Transaction tx = TransactionsApi.getTransactionById(txId);
		//in case of CREATE operation, tx id is the asset id
		if(tx.getOperation().contains(Operations.CREATE.name())) {
			assetId = tx.getId();
		}
		//in case of TRANSFER operation, asset id is stored in asset object
		else {
			assetId = tx.getAsset().getId();
		}
		
		return assetId;
	}
```
If above snippet, solved your issue, then please close this issue.

**Comment by ghost** [comment]
Thanks for explanation @innoprenuer!
